### ISSUE TITLE
Error when running code with new reflectance 

### ISSUE THREAD

**Issue by adrianlar** [rorymclaurin/Thermal-Model#13]
Hi Rory, 
Code is not able to run, it comes up with this error:
Networks2,are merged networks
Warning: Matrix is singular, close to singular or badly scaled. Results may be inaccurate. RCOND = NaN. 
> In network_rad (line 40)
  In landerthermal2 (line 113)
Operation terminated by user during landerthermal2 (line 163)

I don't know if its something with the data entry or a parameter i changed on the landerthermal2 file, we can have a meeting about this tmr if need be.

**Comment by rorymclaurin** [comment]
Hey Adrian, 

I've got that warning before too - it might be an issue with your view factors or it could be something we need to look at fixing in the code. We should definitely meet about it later. Before then - what colour was the warning message?

**Comment by adrianlar** [comment]
Sorry there was an empty cell, my bad.
