### ISSUE TITLE
PSR Temperature and Conditions

### ISSUE THREAD

**Issue by adrianlar** [rorymclaurin/Thermal-Model#7]
Hi Rory, 
Was wondering if there was a way to change the code to test the rover in a PSR?

If it requires too much work before the CDR next week, that can be something to do post-CDR so its no hassle if so

**Comment by rorymclaurin** [comment]
Hi Adrian,
The horizon_angle variable should be able to help you with this. 
If you want to simulate a real crater and test if it's a PSR, you can set it based on the height of the crater.
If you just want to simulate total darkness, set the horizon angle to 90 degrees - this will block the sun out at any point in it's trajectory
The horizon_angle variable is just after the latitude and longitude settings in landerthermal2.m - just change it over before you run

**Comment by adrianlar** [comment]
> Hi Adrian,
> The horizon_angle variable should be able to help you with this.
> If you want to simulate a real crater and test if it's a PSR, you can set it based on the height of the crater.
> If you just want to simulate total darkness, set the horizon angle to 90 degrees - this will block the sun out at any point in it's trajectory
> The horizon_angle variable is just after the latitude and longitude settings in landerthermal2.m - just change it over before you run

Do you mean Horizon_Elevation? I can't find Horizon_angle variable

**Comment by rorymclaurin** [comment]
Ah sorry yes I do - wrong name! Let me know if that works out and if not maybe we can have look together tomorrow.

**Comment by adrianlar** [comment]
Tested it now. All components that are on the outside, i.e. structure got a significant drop in temp. 
However, when i tested the difference with the WEB, temperature did not drop when in PSR.

**Comment by rorymclaurin** [comment]
Ok - if the external temperatures are dropping then it sounds like the PSR is in effect, but it's interesting that you aren't seeing any change in the WEB. Off the top of my head, I would guess that something unrelated is causing the WEB not to respond properly, but I'm happy to take a look tomorrow

**Comment by adrianlar** [comment]
![Vital Temp with Heat Generation 2 with Thermal Bridge](https://user-images.githubusercontent.com/67707346/89123793-0294a600-d4ca-11ea-9561-b8955526f24a.JPG)
![Vital Temp with Heat Generation 2 with Thermal Bridge PSR](https://user-images.githubusercontent.com/67707346/89123795-04f70000-d4ca-11ea-99c1-7172b38aae4d.JPG)
Yea the structure and the drill temperature drops I understand work and make sense, just don't get why both the RTG and WEB dont change. Here are the two images to show, one in regular daytime/night and the other in PSR
